const subscriptions = {
  REQUEST_PENDING: 'REQUEST_PENDING',
  REQUEST_DONE: 'REQUEST_DONE',
  DOM_READY: 'DOM_READY',

  FETCH_PARCELS_REQUEST: 'FETCH_PARCELS_REQUEST',
  FETCH_PARCELS_SUCCESS: 'FETCH_PARCELS_SUCCESS',
  FETCH_PARCELS_FAILURE: 'FETCH_PARCELS_FAILURE',

  FETCH_USER_PARCELS_REQUEST: 'FETCH_USER_PARCELS_REQUEST',
  FETCH_USER_PARCELS_SUCCESS: 'FETCH_USER_PARCELS_SUCCESS',
  FETCH_USER_PARCELS_FAILURE: 'FETCH_USER_PARCELS_FAILURE',

  FETCH_USER_PROFILE_REQUEST: 'FETCH_USER_PROFILE_REQUEST',
  FETCH_USER_PROFILE_SUCCESS: 'FETCH_USER_PROFILE_SUCCESS',
  FETCH_USER_PROFILE_FAILURE: 'FETCH_USER_PROFILE_FAILURE',

  FETCH_PARCEL_REQUEST: 'FETCH_PARCEL_REQUEST',
  FETCH_PARCEL_SUCCESS: 'FETCH_PARCEL_SUCCESS',
  FETCH_PARCEL_FAILURE: 'FETCH_PARCEL_FAILURE',

  CANCEL_PARCEL_ORDER_REQUEST: 'CANCEL_PARCEL_ORDER_REQUEST',
  CANCEL_PARCEL_ORDER_SUCCESS: 'CANCEL_PARCEL_ORDER_SUCCESS',
  CANCEL_PARCEL_ORDER_FAILURE: 'CANCEL_PARCEL_ORDER_FAILURE',

  EDIT_PARCEL_ORDER_REQUEST: 'EDIT_PARCEL_ORDER_REQUEST',
  EDIT_PARCEL_ORDER_SUCCESS: 'EDIT_PARCEL_ORDER_SUCCESS',
  EDIT_PARCEL_ORDER_FAILURE: 'EDIT_PARCEL_ORDER_FAILURE',

  PAGINATION_TARGET_SELECTED: 'PAGINATION_TARGET_SELECTED',

  MAP_SCRIPT_READY: 'MAP_SCRIPT_READY'
}

export default subscriptions;