const subscriptions = {
  REQUEST_PENDING: 'REQUEST_PENDING',
  REQUEST_DONE: 'REQUEST_DONE',

  FETCH_PARCELS_REQUEST: 'FETCH_PARCELS_REQUEST',
  FETCH_PARCELS_SUCCESS: 'FETCH_PARCELS_SUCCESS',
  FETCH_PARCELS_FAILURE: 'FETCH_PARCELS_FAILURE',

  FETCH_USER_PARCELS_REQUEST: 'FETCH_USER_PARCELS_REQUEST',
  FETCH_USER_PARCELS_SUCCESS: 'FETCH_USER_PARCELS_SUCCESS',
  FETCH_USER_PARCELS_FAILURE: 'FETCH_USER_PARCELS_FAILURE',

  FETCH_PARCEL_REQUEST: 'FETCH_PARCEL_REQUEST',
  FETCH_PARCEL_SUCCESS: 'FETCH_PARCEL_SUCCESS',
  FETCH_PARCEL_FAILURE: 'FETCH_PARCEL_FAILURE',
}

export default subscriptions;