engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      similar-code:
        enabled: false
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM
exclude_patherns:
- "node_modules/"
- ".nyc_output"
- "coverage"
- "server/**/specs/"
- ".vscode"