sudo: required
language: node_js
node_js:
  - "8.9.4"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
  - npm install mocha-lcov-reporter --save-dev
  - npm install -g nyc
  - npm install -g babel-cli
  - npm install -g coveralls
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc --reporter=lcov npm run test

after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
