sudo: required
language: node_js
node_js:
  - "8.9.4"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
env:
  global:
  - CC_TEST_REPORTER_ID=5c1c64ea6750a5b25ea64441ce66d630440648e3e0f946ad2619a7e910fc81b2
  - NODE_ENV=test
  - MODE=online
  - JWT_SECRET_KEY=CdxLE.EWW@$$WGGjzwbsswCT
  - TEST_DATABASE_URL=postgres://fjwmupwoecntsv:3f7ef3d35ed2c13036f7eacd0a9cf10c16c60b08ecbbccc9981802b510f45f33@ec2-54-235-193-34.compute-1.amazonaws.com:5432/d7sgj6q1ofrn5f
before_script:
  - npm install
  - npm install mocha-lcov-reporter --save-dev
  - npm install -g nyc
  - npm install -g babel-cli
  - npm install -g coveralls
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc --reporter=lcov npm run test

after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
